// <auto-generated />
using System;
using IWork.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IWork.Migrations
{
    [DbContext(typeof(IWorkDbContext))]
    [Migration("20230225085935_Change_employersmodel_and_new_applymodel")]
    partial class Change_employersmodel_and_new_applymodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("IWork.Models.ApplyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applys");
                });

            modelBuilder.Entity("IWork.Models.EmployerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("FPTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImage = "/images/fss-logo.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Education",
                            Image1 = "/images/fss1.png",
                            Image2 = "/images/fss1.png",
                            Name = "society number 1",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CoverImage = "/images/fss-logo.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Part Time",
                            Field = "Education",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 2",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CoverImage = "/images/fss-logo.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Education",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 3",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CoverImage = "/images/trip1.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Computer science",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 4",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CoverImage = "/images/trip1.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Computer science",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 5",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CoverImage = "/images/trip1.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Computer science",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 6",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CoverImage = "/images/trip2.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Medical",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 7",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CoverImage = "/images/trip2.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Medical",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 8",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CoverImage = "/images/trip2.png",
                            Description = "this is a dumb text description for development gangy",
                            Email = "society1@Gmail.com",
                            FPTime = "Full Time",
                            Field = "Medical",
                            Image1 = "",
                            Image2 = "",
                            Name = "society number 9",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
